### ISSUE TITLE
The app cuts off the some functionalities in landscape mode

### ISSUE THREAD

**Issue by fabianmani** [JohnLines/mediclog#13]
#### Expected behavior
When i switch to landscape screen i should be able to use the app's functions.

#### Actual behavior
Some of the app's functions are cut off in landscape mode(temperature and weight cant be accessed. even the save, send and delete buttons).

#### How to reproduce
* download the app
* open the app and turn your screen to landscape mode.

* Device : tecno k7
* Operating system: Android 7.0
* App Version : 0.2.0 (latest version, updated 4days ago) 

#### Recording Of The Bug
https://youtu.be/UKCV4U51XFQ.
    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@fabianmani/the-app-cuts-off-the-some-functionalities-in-landscape-mode">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by JohnLines** [comment]
Main window now scrolling - closed in 0.2.2
