### ISSUE TITLE
Delete option is not working.

### ISSUE THREAD

**Issue by PeerzadaZeeshan** [JohnLines/mediclog#15]
#### Expected behavior
On pressing on delete option it must be deleted. 

#### Actual behavior

After pressing on delete option it shows nothing or it is not working. 

#### How to reproduce
Install the app from f droid 

Open it

Press on delete option 

It does not work. 

* Browser: medic log
* Version:0.2.1
* Operating system:5.1.1

#### Recording Of The Bug
https://youtu.be/niZMRVVeZ1Q
    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@peerzadazeeshan/delete-option-is-not-working">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by JohnLines** [comment]
Medic log is an application which records key medical information into a file on your Android device. The Delete button is provided to enable that data to be deleted. If no data has been saved there is nothing to delete, hence the button does nothing.

**Comment by JohnLines** [comment]
Delete button (and Send button) now only displayed when there is a file to delete or send. Commit af403f4
