### ISSUE TITLE
History option is not working. 

### ISSUE THREAD

**Issue by PeerzadaZeeshan** [JohnLines/mediclog#16]
#### Expected behavior
On tapping the history option it must show the privious history regarding app. 

#### Actual behavior
Want to check my previous history,when tapping on history option it doesn't work. 

#### How to reproduce 
Install the app from f droid. 

Open the  app and do some work on it. 

Then click on history option. 

It doesn't  work. 

* Browser: Medic log
* Version:0.2.1
* Operating system:5.1.1

#### Recording Of The Bug
https://youtu.be/Rrc1y0y8bCg

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@peerzadazeeshan/history-option-is-not-working">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by JohnLines** [comment]
History is not yet implemented  - see #1 and #9 - Menu option disabled except for debug builds until it is ready. 

Closed in 0.2.2
