### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by mimi89999** [JohnLines/mediclog#17]
Building the app fails with `/home/vagrant/build/org.paladyn.mediclog/src/main/res/layout_land/mediclog_layout.xml: Error: Unsupported type 'TextView'`.

Full build log: https://f-droid.org/wiki/page/org.paladyn.mediclog/lastbuild_5

**Comment by JohnLines** [comment]
Closed in version 0.2.3 - directory renamed from layout_land to layout-land, which has fixed it. New version build in my build server
