### ISSUE TITLE
Bug : time zone refuses to change to utc time zone 

### ISSUE THREAD

**Issue by jubreal** [JohnLines/mediclog#18]
#### Expected behavior

When the time zone is set to utc zone , the in-app time for records should be in utc time zone (gmt zone)  and not the local time zone of the geographic location of the user as the app have this feature present. 

#### Actual behavior

The time zone refuses to change from the local time zone to the utc (gmt) time zone. Which means this feature does not work like it's supposed to. 

#### How to reproduce

1. Download the app from fdroid 

2. Launch the app 

3. Click on the menu icon (3 dots on the top right corner) 

4. Click on preferences 

5. Check the box for time in utc. 

6. Compare the in-app time with the local time of your zone. (It is the same with the local time zone , my own local time zone is gmt +1) 

9. You can repeat the process of checking and unchecking the utc time zone box, the result remains the same as time refuses to change to utc time zone. 

* Browser: medic log App version 0.2.1
* Operating system: Android version 6.0 infinix Note 3

#### Recording Of The Bug

https://youtu.be/q7NZvpX3-i4    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@jubreal/bug-time-zone-refuses-to-change-to-utc-time-zone">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by tobias-g1** [comment]
Hello, I'm one of the moderators at Utopian and I thought it would be useful if I provided some additional information surrounding this issue which I believe you may find useful. Although this particular contribution provides information surrounding the medical record shown in the add medical log screen I also conducted testing surrounding the times being saved correctly to the csv file, please see my test steps below:

1. Download & Launch
2.  Go to preferences
3. Ensure UTC is checked
4. Create medical record
5. Save Medical Record
6. Send Medical Record, Name Medical UTC Time
7. Choose Google Drive 
8. Once it has been uploaded, the clear data cache for application
9. Launch app
10. Ensure save a UTC is not checked
11. Create medical record
12. Save Medical Record
13. Send Medical Record
14. Choose Google Drive, Name Medical Local Time
15. Go to Google Drive
16. Open "Medical UTC Time" and check time column
17. Open "Medical Medical Local Time" and check time column

#### Expected Result

The "Medical UTC Time" should be logged in UTC time and "Medical Local Time" records should be logged at your local device time.

#### Actual Result

Records saved in both Medical UTC Time & Medical Local Time are saved in local time.

#### Enviroment 

Application Version: 2.0
Operating system: Android 5.0.2
Device: Samsung Galaxy Alpha
Model Number: SM-G850

I would also like to note that there was some question surrounding whether this was a bug although I believe if it would be best for you to decide in light of both mine and the contributor's findings. If you have any further questions about the bug I'm sure both I and the contributor would be happy to help. 

I've seen previously that some of the contributions that have been provided to your project via Utopian have been less than satisfactory and would like to welcome any questions or improvements you would like to see to issues submitted to via Utopian. 

Thanks,
Tobias

**Comment by JohnLines** [comment]
Thank you, as I live in the GMT time zone, this was not obvious, even with the switch to Summer Time. I have now seen this myself.

 I will be returning from Greece shortly and will have a better chance to work on a fix

John

On 9 April 2018 00:06:28 EEST, tobias-g1 <notifications@github.com> wrote:
>Hello, I'm one of the moderators at Utopian and I thought it would be
>useful if I provided some additional information surrounding this issue
>which I believe you may find useful. Although this particular
>contribution provides information surrounding the medical record shown
>in the add medical log screen I also conducted testing surrounding the
>times being saved correctly to the csv file, please see my test steps
>below:
>
>1. Download & Launch
>2.  Go to preferences
>3. Ensure UTC is checked
>4. Create medical record
>5. Save Medical Record
>6. Send Medical Record, Name Medical UTC Time
>7. Choose Google Drive 
>8. Once it has been uploaded, the clear data cache for application
>9. Launch app
>10. Ensure save a UTC is not checked
>11. Create medical record
>12. Save Medical Record
>13. Send Medical Record
>14. Choose Google Drive, Name Medical Local Time
>15. Go to Google Drive
>16. Open "Medical UTC Time" and check time column
>17. Open "Medical Medical Local Time" and check time column
>
>#### Expected Result
>
>The "Medical UTC Time" should be logged in UTC time and "Medical Local
>Time" records should be logged at your local device time.
>
>#### Actual Result
>
>Records saved in both Medical UTC Time & Medical Local Time are saved
>in local time.
>
>#### Enviroment 
>
>Application Version: 2.0
>Operating system: Android 5.0.2
>Device: Samsung Galaxy Alpha
>Model Number: SM-G850
>
>I would also like to note that there was some question surrounding
>whether this was a bug although I believe if it would be best for you
>to decide in light of both mine and the contributor's findings. If you
>have any further questions about the bug I'm sure both I and the
>contributor would be happy to help. 
>
>I've seen previously that some of the contributions that have been
>provided to your project via Utopian have been less than satisfactory
>and would like to welcome any questions or improvements you would like
>to see to issues submitted to via Utopian. 
>
>Thanks,
>Tobias
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/JohnLines/mediclog/issues/18#issuecomment-379582633

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by JohnLines** [comment]
Fixed in version 0.2.3
