### ISSUE TITLE
"Failed to install..."

### ISSUE THREAD

**Issue by brs19301** [JohnLines/mediclog#34]
Hi John,
The latest version of MedicLog will not install from F-Droid and the app is not to be found on the AuroraStore (Google play store).
removing the previous app, rebooting and trying to reinstall does not work.  error message...
"Failed to install due to an unknown error"

OS here: LineageOS 20... (android 13)
Phone: Oneplus 9pro "LE2125"

Thnx for the useful app.

**Comment by MDKAOD** [comment]
+1

**Comment by JohnLines** [comment]
The latest build of mediclog runs on android 13 in an emulator, and is now available in F-Droid - could you try it and let me know if it works ?

Thank you

**Comment by MDKAOD** [comment]
Looks like the issue has been resolved. Nice work, and thank you.

**Comment by JohnLines** [comment]
Closing as mediclog appears to install on Android 13 now
