### ISSUE TITLE
Clear button crash

### ISSUE THREAD

**Issue by dirtygardner** [JohnLines/mediclog#8]
Clicking any of the + or - buttons next to a field that has been cleared causes the app to crash. 
SAMSUNG-SGH-I747 Android 4.4.2

**Comment by JohnLines** [comment]
If the field is clear then pressing + or - will set it to a default value, before incrementing or decrementing it. Fixed in version 0.2.1

**Comment by JohnLines** [comment]
v0.2.1 uploaded to Google Play and F-Droid
